# Generated by Django 5.1 on 2024-08-30 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_category_product_catagory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catagory',
            new_name='Catagory',
        ),
    ]
