# Generated by Django 5.1 on 2024-09-24 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_contactmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='full_name',
            new_name='name',
        ),
    ]
