# Generated by Django 5.1 on 2024-09-24 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
