# Generated by Django 5.1 on 2024-10-02 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_userorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserOrder',
        ),
    ]
